

# ── SK-06 Claim Readiness Validator — auto-generated ──────────────────────────
# Generated by scripts/generate_skill_lambda.py from sk-06-claim-readine.md

data "archive_file" "skill_claim_readine" {
  type        = "zip"
  source_dir  = "${path.module}/../lambda/skills/claim_readine"
  output_path = "${path.module}/../.build/skill_claim_readine.zip"
}

resource "aws_lambda_function" "skill_claim_readine" {
  function_name    = "llmwiki-skill-sk06-claim-readine"
  role             = aws_iam_role.skills_lambda.arn
  handler          = "handler.lambda_handler"
  runtime          = "python3.12"
  filename         = data.archive_file.skill_claim_readine.output_path
  source_code_hash = data.archive_file.skill_claim_readine.output_base64sha256
  timeout          = 120
  memory_size      = 512

  environment {
    variables = {
      LOG_TABLE = aws_dynamodb_table.wiki_log.name
  BEDROCK_MODEL_ID = var.bedrock_model_id
  # TODO: add table env vars for this skill
  # TODO: add SNS_TOPIC_ARN for this skill
    }
  }

  tags = {
    skill_id      = "SK-06-placeholder"
    tier          = "3"
    use_case_tags = "UC5_UC8"
    generated_by  = "generate_skill_lambda.py"
  }
}

resource "aws_cloudwatch_log_group" "skill_claim_readine" {
  name              = "/aws/lambda/llmwiki-skill-sk06-claim-readine"
  retention_in_days = 30
}
# Note: sk06_arn SSM parameter is defined in pm_problem_mgnt.tf (real SK-06 classifier)
